version: 0.2
env:
  variables:
    DOCKER_REGISTRY: 'devmusawir'
    DOCKER_IMAGE: 'products-app'
    DEPLOY_K8S_PLAYBOOK: 'ansible/playbooks/deploy_k8s.yml'
    K8S_MONITORING_PLAYBOOK: 'ansible/playbooks/setup_monitoring.yml'
    ANSIBLE_INVENTORY_PATH: 'ansible/inventory.ini'
  secrets-manager:
    DOCKER_USERNAME: 'dockerhub-credentials-id:username'  # Store in AWS Secrets Manager
    DOCKER_PASSWORD: 'dockerhub-credentials-id:password'
    # SUDO_PASSWORD: 'SUDO_PASSWORD'
    VAULT_PASSWORD: 'vault-password-id'

phases:
  install:
    runtime-versions:
      java: corretto11  # Amazon Corretto JDK
    commands:
      # Install required tools
      - apt-get update -y
      - apt-get install -y docker.io ansible
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

  pre_build:
    commands:
      # Docker login using secrets
      - echo "Authenticating to Docker Hub..."
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Create Ansible vault password file
      - echo "$VAULT_PASSWORD" > vault_pass.txt
      - chmod 600 vault_pass.txt

  # build:
  #   commands:
  #     # Maven build steps
  #     - mvn clean install -Dmaven.test.skip=true
  #     - mvn test
  #     - mvn clean package -Dmaven.test.skip=true

  #     # Docker build
  #     - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE:latest .

  # post_build:
  #   commands:
  #     # Push Docker image
  #     - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:latest

  #     # Kubernetes deployment
  #     - ansible-playbook $DEPLOY_K8S_PLAYBOOK \
  #         -i $ANSIBLE_INVENTORY_PATH \
  #         --extra-vars "ansible_become_pass=$SUDO_PASSWORD" \
  #         -v

  #     # Monitoring setup with vault
  #     - ansible-playbook $K8S_MONITORING_PLAYBOOK \
  #         -i $ANSIBLE_INVENTORY_PATH \
  #         --extra-vars "ansible_become_pass=$SUDO_PASSWORD" \
  #         --vault-password-file vault_pass.txt \
  #         -v

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'  # Maven cache
    - '/root/.docker/**/*'  # Docker cache